"""
Generates src/model/unicode_tables.inc: the Unicode data the tokenizer needs.

  - character classes for the pre-tokenizer regex: letters (\\p{L}),
    numbers (\\p{N}) and white space (\\s = the White_Space property);
  - NFC normalization data: canonical combining classes, full canonical
    decompositions, and primary composites.

Run it with the Python whose Unicode version you want to match:
    python scripts/gen_unicode_tables.py
"""
import os
import sys
import unicodedata

MAX_CP = 0x110000
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "model", "unicode_tables.inc")

# White_Space property (PropList.txt); \s in the tokenizer's regex engine.
WHITE_SPACE = [(0x09, 0x0D), (0x20, 0x20), (0x85, 0x85), (0xA0, 0xA0), (0x1680, 0x1680),
               (0x2000, 0x200A), (0x2028, 0x2029), (0x202F, 0x202F), (0x205F, 0x205F), (0x3000, 0x3000)]


def ranges(pred):
    out, start = [], None
    for cp in range(MAX_CP):
        if 0xD800 <= cp <= 0xDFFF:
            ok = False
        else:
            ok = pred(cp)
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX_CP - 1))
    return out


def full_decomposition(cp):
    d = unicodedata.decomposition(chr(cp))
    if not d or d.startswith("<"):
        return [cp]
    out = []
    for part in d.split():
        out.extend(full_decomposition(int(part, 16)))
    return out


def main():
    letters = ranges(lambda cp: unicodedata.category(chr(cp)).startswith("L"))
    numbers = ranges(lambda cp: unicodedata.category(chr(cp)).startswith("N"))

    ccc = ranges(lambda cp: unicodedata.combining(chr(cp)) != 0)
    ccc_vals = []
    for lo, hi in ccc:
        # split ranges so each one has a single class value
        cur_lo, cur_val = lo, unicodedata.combining(chr(lo))
        for cp in range(lo + 1, hi + 1):
            v = unicodedata.combining(chr(cp))
            if v != cur_val:
                ccc_vals.append((cur_lo, cp - 1, cur_val))
                cur_lo, cur_val = cp, v
        ccc_vals.append((cur_lo, hi, cur_val))

    decomp = []  # (cp, [cps]) for canonical decompositions, excluding Hangul (algorithmic)
    compose = []  # (first, second, composite)
    for cp in range(MAX_CP):
        if 0xAC00 <= cp <= 0xD7A3 or 0xD800 <= cp <= 0xDFFF:
            continue
        d = unicodedata.decomposition(chr(cp))
        if not d or d.startswith("<"):
            continue
        decomp.append((cp, full_decomposition(cp)))
        parts = [int(p, 16) for p in d.split()]
        # A primary composite: NFC recomposes its own canonical decomposition into it.
        if len(parts) == 2 and unicodedata.normalize("NFC", chr(parts[0]) + chr(parts[1])) == chr(cp):
            compose.append((parts[0], parts[1], cp))
    compose.sort()

    pool, offsets = [], []
    for cp, cps in decomp:
        offsets.append((cp, len(pool), len(cps)))
        pool.extend(cps)

    def emit_ranges(f, name, rs):
        f.write(f"static const uint32_t {name}[][2] = {{\n")
        for i in range(0, len(rs), 6):
            f.write("    " + " ".join(f"{{0x{a:X}, 0x{b:X}}}," for a, b in rs[i:i + 6]) + "\n")
        f.write("};\n\n")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(f"// Generated by scripts/gen_unicode_tables.py from Unicode {unicodedata.unidata_version}.\n")
        f.write("// Do not edit by hand.\n\n")
        f.write(f"#define EMBER_UNICODE_VERSION \"{unicodedata.unidata_version}\"\n\n")
        emit_ranges(f, "kLetterRanges", letters)
        emit_ranges(f, "kNumberRanges", numbers)
        emit_ranges(f, "kWhiteSpaceRanges", WHITE_SPACE)
        f.write("static const uint32_t kCccRanges[][3] = {\n")
        for i in range(0, len(ccc_vals), 5):
            f.write("    " + " ".join(f"{{0x{a:X}, 0x{b:X}, {v}}}," for a, b, v in ccc_vals[i:i + 5]) + "\n")
        f.write("};\n\n")
        f.write("static const uint32_t kDecompPool[] = {\n")
        for i in range(0, len(pool), 10):
            f.write("    " + " ".join(f"0x{c:X}," for c in pool[i:i + 10]) + "\n")
        f.write("};\n\n")
        f.write("// code point, offset into kDecompPool, length\n")
        f.write("static const uint32_t kDecomp[][3] = {\n")
        for i in range(0, len(offsets), 5):
            f.write("    " + " ".join(f"{{0x{a:X}, {b}, {c}}}," for a, b, c in offsets[i:i + 5]) + "\n")
        f.write("};\n\n")
        f.write("// first, second, composite (sorted by first, then second)\n")
        f.write("static const uint32_t kCompose[][3] = {\n")
        for i in range(0, len(compose), 4):
            f.write("    " + " ".join(f"{{0x{a:X}, 0x{b:X}, 0x{c:X}}}," for a, b, c in compose[i:i + 4]) + "\n")
        f.write("};\n")
    print(f"wrote {OUT}: {len(letters)} letter ranges, {len(numbers)} number ranges, "
          f"{len(ccc_vals)} ccc ranges, {len(decomp)} decompositions, {len(compose)} compositions "
          f"(Unicode {unicodedata.unidata_version})")


if __name__ == "__main__":
    sys.exit(main())
